package aplicacion.datos.hibernate.mapeos;
// Generated 11/06/2018 16:25:57 by Hibernate Tools 4.3.1



/**
 * AulasMaterias generated by hbm2java
 */
public class AulasMaterias  implements java.io.Serializable {


     private Integer amCodigo;
     private String amPeriodo;
     private String amComentario;
     private String amDia;
     private String amHorarioDesde;
     private String amHorarioHasta;
     private boolean amEstado;
     private int amAsignacionMateria;
     private int amAula;
     private String amFranjaHoraria;

    public AulasMaterias() {
    }

    public AulasMaterias(String amPeriodo, String amComentario, String amDia, String amHorarioDesde, String amHorarioHasta, boolean amEstado, int amAsignacionMateria, int amAula, String amFranjaHoraria) {
       this.amPeriodo = amPeriodo;
       this.amComentario = amComentario;
       this.amDia = amDia;
       this.amHorarioDesde = amHorarioDesde;
       this.amHorarioHasta = amHorarioHasta;
       this.amEstado = amEstado;
       this.amAsignacionMateria = amAsignacionMateria;
       this.amAula = amAula;
       this.amFranjaHoraria = amFranjaHoraria;
    }
   
    public Integer getAmCodigo() {
        return this.amCodigo;
    }
    
    public void setAmCodigo(Integer amCodigo) {
        this.amCodigo = amCodigo;
    }
    public String getAmPeriodo() {
        return this.amPeriodo;
    }
    
    public void setAmPeriodo(String amPeriodo) {
        this.amPeriodo = amPeriodo;
    }
    public String getAmComentario() {
        return this.amComentario;
    }
    
    public void setAmComentario(String amComentario) {
        this.amComentario = amComentario;
    }
    public String getAmDia() {
        return this.amDia;
    }
    
    public void setAmDia(String amDia) {
        this.amDia = amDia;
    }
    public String getAmHorarioDesde() {
        return this.amHorarioDesde;
    }
    
    public void setAmHorarioDesde(String amHorarioDesde) {
        this.amHorarioDesde = amHorarioDesde;
    }
    public String getAmHorarioHasta() {
        return this.amHorarioHasta;
    }
    
    public void setAmHorarioHasta(String amHorarioHasta) {
        this.amHorarioHasta = amHorarioHasta;
    }
    public boolean isAmEstado() {
        return this.amEstado;
    }
    
    public void setAmEstado(boolean amEstado) {
        this.amEstado = amEstado;
    }
    public int getAmAsignacionMateria() {
        return this.amAsignacionMateria;
    }
    
    public void setAmAsignacionMateria(int amAsignacionMateria) {
        this.amAsignacionMateria = amAsignacionMateria;
    }
    public int getAmAula() {
        return this.amAula;
    }
    
    public void setAmAula(int amAula) {
        this.amAula = amAula;
    }
    public String getAmFranjaHoraria() {
        return this.amFranjaHoraria;
    }
    
    public void setAmFranjaHoraria(String amFranjaHoraria) {
        this.amFranjaHoraria = amFranjaHoraria;
    }




}


