package aplicacion.datos.hibernate.mapeos;
// Generated 11/06/2018 16:25:57 by Hibernate Tools 4.3.1



/**
 * Aulas generated by hbm2java
 */
public class Aulas  implements java.io.Serializable {


     private Integer aulCodigo;
     private String aulNombre;
     private String aulDescripcion;
     private int aulCapacidad;
     private boolean aulEstado;

    public Aulas() {
    }

    public Aulas(String aulNombre, String aulDescripcion, int aulCapacidad, boolean aulEstado) {
       this.aulNombre = aulNombre;
       this.aulDescripcion = aulDescripcion;
       this.aulCapacidad = aulCapacidad;
       this.aulEstado = aulEstado;
    }
   
    public Integer getAulCodigo() {
        return this.aulCodigo;
    }
    
    public void setAulCodigo(Integer aulCodigo) {
        this.aulCodigo = aulCodigo;
    }
    public String getAulNombre() {
        return this.aulNombre;
    }
    
    public void setAulNombre(String aulNombre) {
        this.aulNombre = aulNombre;
    }
    public String getAulDescripcion() {
        return this.aulDescripcion;
    }
    
    public void setAulDescripcion(String aulDescripcion) {
        this.aulDescripcion = aulDescripcion;
    }
    public int getAulCapacidad() {
        return this.aulCapacidad;
    }
    
    public void setAulCapacidad(int aulCapacidad) {
        this.aulCapacidad = aulCapacidad;
    }
    public boolean isAulEstado() {
        return this.aulEstado;
    }
    
    public void setAulEstado(boolean aulEstado) {
        this.aulEstado = aulEstado;
    }




}


