package aplicacion.datos.hibernate.mapeos;
// Generated 11/06/2018 16:25:57 by Hibernate Tools 4.3.1



/**
 * Carreras generated by hbm2java
 */
public class Carreras  implements java.io.Serializable {


     private Integer carCodigo;
     private String carNombre;
     private String carPlan;
     private boolean carEstado;

    public Carreras() {
    }

    public Carreras(String carNombre, String carPlan, boolean carEstado) {
       this.carNombre = carNombre;
       this.carPlan = carPlan;
       this.carEstado = carEstado;
    }
   
    public Integer getCarCodigo() {
        return this.carCodigo;
    }
    
    public void setCarCodigo(Integer carCodigo) {
        this.carCodigo = carCodigo;
    }
    public String getCarNombre() {
        return this.carNombre;
    }
    
    public void setCarNombre(String carNombre) {
        this.carNombre = carNombre;
    }
    public String getCarPlan() {
        return this.carPlan;
    }
    
    public void setCarPlan(String carPlan) {
        this.carPlan = carPlan;
    }
    public boolean isCarEstado() {
        return this.carEstado;
    }
    
    public void setCarEstado(boolean carEstado) {
        this.carEstado = carEstado;
    }




}


