package aplicacion.datos.hibernate.mapeos;
// Generated 11/06/2018 16:25:57 by Hibernate Tools 4.3.1



/**
 * Docentes generated by hbm2java
 */
public class Docentes  implements java.io.Serializable {


     private Integer docCodigo;
     private String docLegajo;
     private String docCargo;
     private boolean docEstado;
     private int docPerfil;

    public Docentes() {
    }

    public Docentes(String docLegajo, String docCargo, boolean docEstado, int docPerfil) {
       this.docLegajo = docLegajo;
       this.docCargo = docCargo;
       this.docEstado = docEstado;
       this.docPerfil = docPerfil;
    }
   
    public Integer getDocCodigo() {
        return this.docCodigo;
    }
    
    public void setDocCodigo(Integer docCodigo) {
        this.docCodigo = docCodigo;
    }
    public String getDocLegajo() {
        return this.docLegajo;
    }
    
    public void setDocLegajo(String docLegajo) {
        this.docLegajo = docLegajo;
    }
    public String getDocCargo() {
        return this.docCargo;
    }
    
    public void setDocCargo(String docCargo) {
        this.docCargo = docCargo;
    }
    public boolean isDocEstado() {
        return this.docEstado;
    }
    
    public void setDocEstado(boolean docEstado) {
        this.docEstado = docEstado;
    }
    public int getDocPerfil() {
        return this.docPerfil;
    }
    
    public void setDocPerfil(int docPerfil) {
        this.docPerfil = docPerfil;
    }




}


