package aplicacion.datos.hibernate.mapeos;
// Generated 11/06/2018 16:25:57 by Hibernate Tools 4.3.1



/**
 * InscripcionesAlumnos generated by hbm2java
 */
public class InscripcionesAlumnos  implements java.io.Serializable {


     private Integer insCodigo;
     private DocentesMaterias docentesMaterias;
     private boolean insEstado;
     private int insAlumno;

    public InscripcionesAlumnos() {
    }

    public InscripcionesAlumnos(DocentesMaterias docentesMaterias, boolean insEstado, int insAlumno) {
       this.docentesMaterias = docentesMaterias;
       this.insEstado = insEstado;
       this.insAlumno = insAlumno;
    }
   
    public Integer getInsCodigo() {
        return this.insCodigo;
    }
    
    public void setInsCodigo(Integer insCodigo) {
        this.insCodigo = insCodigo;
    }
    public DocentesMaterias getDocentesMaterias() {
        return this.docentesMaterias;
    }
    
    public void setDocentesMaterias(DocentesMaterias docentesMaterias) {
        this.docentesMaterias = docentesMaterias;
    }
    public boolean isInsEstado() {
        return this.insEstado;
    }
    
    public void setInsEstado(boolean insEstado) {
        this.insEstado = insEstado;
    }
    public int getInsAlumno() {
        return this.insAlumno;
    }
    
    public void setInsAlumno(int insAlumno) {
        this.insAlumno = insAlumno;
    }




}


