package aplicacion.datos.hibernate.mapeos;
// Generated 11/06/2018 16:25:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private Integer matCodigo;
     private String matNombre;
     private boolean matEstado;
     private int matCarrera;
     private Set docentesMateriases = new HashSet(0);

    public Materias() {
    }

	
    public Materias(String matNombre, boolean matEstado, int matCarrera) {
        this.matNombre = matNombre;
        this.matEstado = matEstado;
        this.matCarrera = matCarrera;
    }
    public Materias(String matNombre, boolean matEstado, int matCarrera, Set docentesMateriases) {
       this.matNombre = matNombre;
       this.matEstado = matEstado;
       this.matCarrera = matCarrera;
       this.docentesMateriases = docentesMateriases;
    }
   
    public Integer getMatCodigo() {
        return this.matCodigo;
    }
    
    public void setMatCodigo(Integer matCodigo) {
        this.matCodigo = matCodigo;
    }
    public String getMatNombre() {
        return this.matNombre;
    }
    
    public void setMatNombre(String matNombre) {
        this.matNombre = matNombre;
    }
    public boolean isMatEstado() {
        return this.matEstado;
    }
    
    public void setMatEstado(boolean matEstado) {
        this.matEstado = matEstado;
    }
    public int getMatCarrera() {
        return this.matCarrera;
    }
    
    public void setMatCarrera(int matCarrera) {
        this.matCarrera = matCarrera;
    }
    public Set getDocentesMateriases() {
        return this.docentesMateriases;
    }
    
    public void setDocentesMateriases(Set docentesMateriases) {
        this.docentesMateriases = docentesMateriases;
    }




}


