package aplicacion.datos.hibernate.mapeos;
// Generated 11/06/2018 16:25:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {


     private Integer perCodigo;
     private String perNombres;
     private String perApellidos;
     private String perDni;
     private Date perFechaNac;
     private String perEmail;
     private String perCelular;
     private int usuario;

    public Perfiles() {
    }

    public Perfiles(String perNombres, String perApellidos, String perDni, Date perFechaNac, String perEmail, String perCelular, int usuario) {
       this.perNombres = perNombres;
       this.perApellidos = perApellidos;
       this.perDni = perDni;
       this.perFechaNac = perFechaNac;
       this.perEmail = perEmail;
       this.perCelular = perCelular;
       this.usuario = usuario;
    }
   
    public Integer getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Integer perCodigo) {
        this.perCodigo = perCodigo;
    }
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }
    public String getPerApellidos() {
        return this.perApellidos;
    }
    
    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }
    public String getPerDni() {
        return this.perDni;
    }
    
    public void setPerDni(String perDni) {
        this.perDni = perDni;
    }
    public Date getPerFechaNac() {
        return this.perFechaNac;
    }
    
    public void setPerFechaNac(Date perFechaNac) {
        this.perFechaNac = perFechaNac;
    }
    public String getPerEmail() {
        return this.perEmail;
    }
    
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail;
    }
    public String getPerCelular() {
        return this.perCelular;
    }
    
    public void setPerCelular(String perCelular) {
        this.perCelular = perCelular;
    }
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }




}


