package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer aluCodigo;
     private Carrera carreras;
     private Perfil perfiles;
     private String aluLibretaUniversitaria;
     private Set inscripcionesAlumnoses = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(Carrera carreras, Perfil perfiles, String aluLibretaUniversitaria) {
        this.carreras = carreras;
        this.perfiles = perfiles;
        this.aluLibretaUniversitaria = aluLibretaUniversitaria;
    }
    public Alumno(Carrera carreras, Perfil perfiles, String aluLibretaUniversitaria, Set inscripcionesAlumnoses) {
       this.carreras = carreras;
       this.perfiles = perfiles;
       this.aluLibretaUniversitaria = aluLibretaUniversitaria;
       this.inscripcionesAlumnoses = inscripcionesAlumnoses;
    }
   
    public Integer getAluCodigo() {
        return this.aluCodigo;
    }
    
    public void setAluCodigo(Integer aluCodigo) {
        this.aluCodigo = aluCodigo;
    }
    public Carrera getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carrera carreras) {
        this.carreras = carreras;
    }
    public Perfil getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfil perfiles) {
        this.perfiles = perfiles;
    }
    public String getAluLibretaUniversitaria() {
        return this.aluLibretaUniversitaria;
    }
    
    public void setAluLibretaUniversitaria(String aluLibretaUniversitaria) {
        this.aluLibretaUniversitaria = aluLibretaUniversitaria;
    }
    public Set getInscripcionesAlumnoses() {
        return this.inscripcionesAlumnoses;
    }
    
    public void setInscripcionesAlumnoses(Set inscripcionesAlumnoses) {
        this.inscripcionesAlumnoses = inscripcionesAlumnoses;
    }




}


