package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer codigo;
     private Carrera carrera;
     private Perfil perfil;
     private String libretaUniversitaria;

    public Alumno() {
    }

	
    public Alumno(Carrera carreras, Perfil perfiles, String aluLibretaUniversitaria) {
        this.carrera = carreras;
        this.perfil = perfiles;
        this.libretaUniversitaria = aluLibretaUniversitaria;
    }
   @Override
    public String toString(){
        return String.format("Alumno[%d,%s]", codigo, carrera,perfil,libretaUniversitaria);
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getLibretaUniversitaria() {
        return this.libretaUniversitaria;
    }
    
    public void setLibretaUniversitaria(String libretaUniversitaria) {
        this.libretaUniversitaria = libretaUniversitaria;
    }

}


