package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AulasMaterias generated by hbm2java
 */
public class AulasMaterias  implements java.io.Serializable {


     private Integer amCodigo;
     private Aula aulas;
     private DocenteMateria docentesMaterias;
     private String amPeriodo;
     private String amComentario;
     private String amDia;
     private String amHorarioDesde;
     private String amHorarioHasta;
     private boolean amEstado;
     private String amFranjaHoraria;
     private Set asistenciases = new HashSet(0);

    public AulasMaterias() {
    }

	
    public AulasMaterias(Aula aulas, DocenteMateria docentesMaterias, String amPeriodo, String amComentario, String amDia, String amHorarioDesde, String amHorarioHasta, boolean amEstado, String amFranjaHoraria) {
        this.aulas = aulas;
        this.docentesMaterias = docentesMaterias;
        this.amPeriodo = amPeriodo;
        this.amComentario = amComentario;
        this.amDia = amDia;
        this.amHorarioDesde = amHorarioDesde;
        this.amHorarioHasta = amHorarioHasta;
        this.amEstado = amEstado;
        this.amFranjaHoraria = amFranjaHoraria;
    }
    public AulasMaterias(Aula aulas, DocenteMateria docentesMaterias, String amPeriodo, String amComentario, String amDia, String amHorarioDesde, String amHorarioHasta, boolean amEstado, String amFranjaHoraria, Set asistenciases) {
       this.aulas = aulas;
       this.docentesMaterias = docentesMaterias;
       this.amPeriodo = amPeriodo;
       this.amComentario = amComentario;
       this.amDia = amDia;
       this.amHorarioDesde = amHorarioDesde;
       this.amHorarioHasta = amHorarioHasta;
       this.amEstado = amEstado;
       this.amFranjaHoraria = amFranjaHoraria;
       this.asistenciases = asistenciases;
    }
   
    public Integer getAmCodigo() {
        return this.amCodigo;
    }
    
    public void setAmCodigo(Integer amCodigo) {
        this.amCodigo = amCodigo;
    }
    public Aula getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Aula aulas) {
        this.aulas = aulas;
    }
    public DocenteMateria getDocentesMaterias() {
        return this.docentesMaterias;
    }
    
    public void setDocentesMaterias(DocenteMateria docentesMaterias) {
        this.docentesMaterias = docentesMaterias;
    }
    public String getAmPeriodo() {
        return this.amPeriodo;
    }
    
    public void setAmPeriodo(String amPeriodo) {
        this.amPeriodo = amPeriodo;
    }
    public String getAmComentario() {
        return this.amComentario;
    }
    
    public void setAmComentario(String amComentario) {
        this.amComentario = amComentario;
    }
    public String getAmDia() {
        return this.amDia;
    }
    
    public void setAmDia(String amDia) {
        this.amDia = amDia;
    }
    public String getAmHorarioDesde() {
        return this.amHorarioDesde;
    }
    
    public void setAmHorarioDesde(String amHorarioDesde) {
        this.amHorarioDesde = amHorarioDesde;
    }
    public String getAmHorarioHasta() {
        return this.amHorarioHasta;
    }
    
    public void setAmHorarioHasta(String amHorarioHasta) {
        this.amHorarioHasta = amHorarioHasta;
    }
    public boolean isAmEstado() {
        return this.amEstado;
    }
    
    public void setAmEstado(boolean amEstado) {
        this.amEstado = amEstado;
    }
    public String getAmFranjaHoraria() {
        return this.amFranjaHoraria;
    }
    
    public void setAmFranjaHoraria(String amFranjaHoraria) {
        this.amFranjaHoraria = amFranjaHoraria;
    }
    public Set getAsistenciases() {
        return this.asistenciases;
    }
    
    public void setAsistenciases(Set asistenciases) {
        this.asistenciases = asistenciases;
    }

 @Override
    public boolean equals(Object other) {
        return (other instanceof AulasMaterias) && (amCodigo != null)
            ? amCodigo.equals(((AulasMaterias) other).amCodigo)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (amCodigo != null)
            ? (this.getClass().hashCode() + amCodigo.hashCode())
            : super.hashCode();
    }

    @Override
    public String toString() {
        return String.format("AulasMaterias[%d, %s]", amCodigo, amComentario);
    }
    


}


