package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private Integer aulCodigo;
     private String aulNombre;
     private String aulDescripcion;
     private int aulCapacidad;
     private boolean aulEstado;
     

    public Aula() {
    }

	
    public Aula(String aulNombre, String aulDescripcion, int aulCapacidad, boolean aulEstado) {
        this.aulNombre = aulNombre;
        this.aulDescripcion = aulDescripcion;
        this.aulCapacidad = aulCapacidad;
        this.aulEstado = aulEstado;
    }
    public Aula(String aulNombre, String aulDescripcion, int aulCapacidad, boolean aulEstado, Set aulasMateriases) {
       this.aulNombre = aulNombre;
       this.aulDescripcion = aulDescripcion;
       this.aulCapacidad = aulCapacidad;
       this.aulEstado = aulEstado;
      
    }
   
    public Integer getAulCodigo() {
        return this.aulCodigo;
    }
    
    public void setAulCodigo(Integer aulCodigo) {
        this.aulCodigo = aulCodigo;
    }
    public String getAulNombre() {
        return this.aulNombre;
    }
    
    public void setAulNombre(String aulNombre) {
        this.aulNombre = aulNombre;
    }
    public String getAulDescripcion() {
        return this.aulDescripcion;
    }
    
    public void setAulDescripcion(String aulDescripcion) {
        this.aulDescripcion = aulDescripcion;
    }
    public int getAulCapacidad() {
        return this.aulCapacidad;
    }
    
    public void setAulCapacidad(int aulCapacidad) {
        this.aulCapacidad = aulCapacidad;
    }
    public boolean isAulEstado() {
        return this.aulEstado;
    }
    
    public void setAulEstado(boolean aulEstado) {
        this.aulEstado = aulEstado;
    }

     @Override
    public boolean equals(Object other) {
        return (other instanceof Aula) && (aulCodigo != null)
            ? aulCodigo.equals(((Aula) other).aulCodigo)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (aulCodigo != null)
            ? (this.getClass().hashCode() + aulCodigo.hashCode())
            : super.hashCode();
    }

    @Override
    public String toString() {
        return String.format("Aula[%d, %s]", aulCodigo, aulNombre);
    }
    



}


