package aplicacion.modelo.dominio;
// Generated 07/06/2018 13:36:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aulas generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private Integer aulCodigo;
     private String aulNombre;
     private String aulDescripcion;
     private int aulCapacidad;
     private boolean aulEstado;
     private Set aulasMateriases = new HashSet(0);

    public Aula() {
    }

	
    public Aula(String aulNombre, String aulDescripcion, int aulCapacidad, boolean aulEstado) {
        this.aulNombre = aulNombre;
        this.aulDescripcion = aulDescripcion;
        this.aulCapacidad = aulCapacidad;
        this.aulEstado = aulEstado;
    }
    public Aula(String aulNombre, String aulDescripcion, int aulCapacidad, boolean aulEstado, Set aulasMateriases) {
       this.aulNombre = aulNombre;
       this.aulDescripcion = aulDescripcion;
       this.aulCapacidad = aulCapacidad;
       this.aulEstado = aulEstado;
       this.aulasMateriases = aulasMateriases;
    }
   
    public Integer getAulCodigo() {
        return this.aulCodigo;
    }
    
    public void setAulCodigo(Integer aulCodigo) {
        this.aulCodigo = aulCodigo;
    }
    public String getAulNombre() {
        return this.aulNombre;
    }
    
    public void setAulNombre(String aulNombre) {
        this.aulNombre = aulNombre;
    }
    public String getAulDescripcion() {
        return this.aulDescripcion;
    }
    
    public void setAulDescripcion(String aulDescripcion) {
        this.aulDescripcion = aulDescripcion;
    }
    public int getAulCapacidad() {
        return this.aulCapacidad;
    }
    
    public void setAulCapacidad(int aulCapacidad) {
        this.aulCapacidad = aulCapacidad;
    }
    public boolean isAulEstado() {
        return this.aulEstado;
    }
    
    public void setAulEstado(boolean aulEstado) {
        this.aulEstado = aulEstado;
    }
    public Set getAulasMateriases() {
        return this.aulasMateriases;
    }
    
    public void setAulasMateriases(Set aulasMateriases) {
        this.aulasMateriases = aulasMateriases;
    }




}


