package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1




/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer codigo;
     private String nombreCarrera;
     private String plan;
     private boolean estado;
     

    public Carrera() {
    }

    public Carrera(Integer codigo, String nombreCarrera, String plan, boolean estado) {
        this.codigo = codigo;
        this.nombreCarrera = nombreCarrera;
        this.plan = plan;
        this.estado = estado;
    }
  @Override
    public String toString(){
        return String.format("Carrera[%d,%s]", codigo, nombreCarrera,plan,estado);
    }

          
    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNombreCarrera() {
        return nombreCarrera;
    }

    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }

    public String getPlan() {
        return plan;
    }

    public void setPlan(String plan) {
        this.plan = plan;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

   

	
   



}


