package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer carCodigo;
     private String carNombre;
     private String carPlan;
     private boolean carEstado;
     private Set materiases = new HashSet(0);
     private Set alumnoses = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(String carNombre, String carPlan, boolean carEstado) {
        this.carNombre = carNombre;
        this.carPlan = carPlan;
        this.carEstado = carEstado;
    }
    public Carrera(String carNombre, String carPlan, boolean carEstado, Set materiases, Set alumnoses) {
       this.carNombre = carNombre;
       this.carPlan = carPlan;
       this.carEstado = carEstado;
       this.materiases = materiases;
       this.alumnoses = alumnoses;
    }
   
    public Integer getCarCodigo() {
        return this.carCodigo;
    }
    
    public void setCarCodigo(Integer carCodigo) {
        this.carCodigo = carCodigo;
    }
    public String getCarNombre() {
        return this.carNombre;
    }
    
    public void setCarNombre(String carNombre) {
        this.carNombre = carNombre;
    }
    public String getCarPlan() {
        return this.carPlan;
    }
    
    public void setCarPlan(String carPlan) {
        this.carPlan = carPlan;
    }
    public boolean isCarEstado() {
        return this.carEstado;
    }
    
    public void setCarEstado(boolean carEstado) {
        this.carEstado = carEstado;
    }
    public Set getMateriases() {
        return this.materiases;
    }
    
    public void setMateriases(Set materiases) {
        this.materiases = materiases;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }




}


