package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docentes generated by hbm2java
 */
public class Docentes  implements java.io.Serializable {


     private Integer docCodigo;
     private Perfil perfiles;
     private String docLegajo;
     private String docCargo;
     private boolean docEstado;
     private Set docentesMateriases = new HashSet(0);

    public Docentes() {
    }

	
    public Docentes(Perfil perfiles, String docLegajo, String docCargo, boolean docEstado) {
        this.perfiles = perfiles;
        this.docLegajo = docLegajo;
        this.docCargo = docCargo;
        this.docEstado = docEstado;
    }
    public Docentes(Perfil perfiles, String docLegajo, String docCargo, boolean docEstado, Set docentesMateriases) {
       this.perfiles = perfiles;
       this.docLegajo = docLegajo;
       this.docCargo = docCargo;
       this.docEstado = docEstado;
       this.docentesMateriases = docentesMateriases;
    }
   
    public Integer getDocCodigo() {
        return this.docCodigo;
    }
    
    public void setDocCodigo(Integer docCodigo) {
        this.docCodigo = docCodigo;
    }
    public Perfil getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfil perfiles) {
        this.perfiles = perfiles;
    }
    public String getDocLegajo() {
        return this.docLegajo;
    }
    
    public void setDocLegajo(String docLegajo) {
        this.docLegajo = docLegajo;
    }
    public String getDocCargo() {
        return this.docCargo;
    }
    
    public void setDocCargo(String docCargo) {
        this.docCargo = docCargo;
    }
    public boolean isDocEstado() {
        return this.docEstado;
    }
    
    public void setDocEstado(boolean docEstado) {
        this.docEstado = docEstado;
    }
    public Set getDocentesMateriases() {
        return this.docentesMateriases;
    }
    
    public void setDocentesMateriases(Set docentesMateriases) {
        this.docentesMateriases = docentesMateriases;
    }




}


