package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DocentesMaterias generated by hbm2java
 */
public class DocentesMaterias  implements java.io.Serializable {


     private Integer dmCodigo;
     private Docentes docentes;
     private Materia materias;
     private int dmAnio;
     private boolean dmHabilitado;
     private boolean dmEstado;
     private Set aulasMateriases = new HashSet(0);
     private Set inscripcionesAlumnoses = new HashSet(0);

    public DocentesMaterias() {
    }

	
    public DocentesMaterias(Docentes docentes, Materia materias, int dmAnio, boolean dmHabilitado, boolean dmEstado) {
        this.docentes = docentes;
        this.materias = materias;
        this.dmAnio = dmAnio;
        this.dmHabilitado = dmHabilitado;
        this.dmEstado = dmEstado;
    }
    public DocentesMaterias(Docentes docentes, Materia materias, int dmAnio, boolean dmHabilitado, boolean dmEstado, Set aulasMateriases, Set inscripcionesAlumnoses) {
       this.docentes = docentes;
       this.materias = materias;
       this.dmAnio = dmAnio;
       this.dmHabilitado = dmHabilitado;
       this.dmEstado = dmEstado;
       this.aulasMateriases = aulasMateriases;
       this.inscripcionesAlumnoses = inscripcionesAlumnoses;
    }
   
    public Integer getDmCodigo() {
        return this.dmCodigo;
    }
    
    public void setDmCodigo(Integer dmCodigo) {
        this.dmCodigo = dmCodigo;
    }
    public Docentes getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Docentes docentes) {
        this.docentes = docentes;
    }
    public Materia getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materia materias) {
        this.materias = materias;
    }
    public int getDmAnio() {
        return this.dmAnio;
    }
    
    public void setDmAnio(int dmAnio) {
        this.dmAnio = dmAnio;
    }
    public boolean isDmHabilitado() {
        return this.dmHabilitado;
    }
    
    public void setDmHabilitado(boolean dmHabilitado) {
        this.dmHabilitado = dmHabilitado;
    }
    public boolean isDmEstado() {
        return this.dmEstado;
    }
    
    public void setDmEstado(boolean dmEstado) {
        this.dmEstado = dmEstado;
    }
    public Set getAulasMateriases() {
        return this.aulasMateriases;
    }
    
    public void setAulasMateriases(Set aulasMateriases) {
        this.aulasMateriases = aulasMateriases;
    }
    public Set getInscripcionesAlumnoses() {
        return this.inscripcionesAlumnoses;
    }
    
    public void setInscripcionesAlumnoses(Set inscripcionesAlumnoses) {
        this.inscripcionesAlumnoses = inscripcionesAlumnoses;
    }




}


