package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DocenteMateria generated by hbm2java
 */
public class DocenteMateria  implements java.io.Serializable {


     private Integer codigo;
     private Docente docente;
     private Materia materia;
     private int anio;
     private boolean habilitado;
     private boolean estado;
   

    public DocenteMateria() {
    }

    public DocenteMateria(Integer codigo, Docente docente, Materia materia, int anio, boolean habilitado, boolean estado) {
        this.codigo = codigo;
        this.docente = docente;
        this.materia = materia;
        this.anio = anio;
        this.habilitado = habilitado;
        this.estado = estado;
    }
    
    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Docente getDocente() {
        return docente;
    }

    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    public Materia getMateria() {
        return materia;
    }

    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    public int getAnio() {
        return anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }

    public boolean isHabilitado() {
        return habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    
   




}


