package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InscripcionesAlumnos generated by hbm2java
 */
public class InscripcionesAlumnos  implements java.io.Serializable {


     private Integer insCodigo;
     private Alumno alumnos;
     private DocentesMaterias docentesMaterias;
     private boolean insEstado;
     private Set asistenciases = new HashSet(0);

    public InscripcionesAlumnos() {
    }

	
    public InscripcionesAlumnos(Alumno alumnos, DocentesMaterias docentesMaterias, boolean insEstado) {
        this.alumnos = alumnos;
        this.docentesMaterias = docentesMaterias;
        this.insEstado = insEstado;
    }
    public InscripcionesAlumnos(Alumno alumnos, DocentesMaterias docentesMaterias, boolean insEstado, Set asistenciases) {
       this.alumnos = alumnos;
       this.docentesMaterias = docentesMaterias;
       this.insEstado = insEstado;
       this.asistenciases = asistenciases;
    }
   
    public Integer getInsCodigo() {
        return this.insCodigo;
    }
    
    public void setInsCodigo(Integer insCodigo) {
        this.insCodigo = insCodigo;
    }
    public Alumno getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumno alumnos) {
        this.alumnos = alumnos;
    }
    public DocentesMaterias getDocentesMaterias() {
        return this.docentesMaterias;
    }
    
    public void setDocentesMaterias(DocentesMaterias docentesMaterias) {
        this.docentesMaterias = docentesMaterias;
    }
    public boolean isInsEstado() {
        return this.insEstado;
    }
    
    public void setInsEstado(boolean insEstado) {
        this.insEstado = insEstado;
    }
    public Set getAsistenciases() {
        return this.asistenciases;
    }
    
    public void setAsistenciases(Set asistenciases) {
        this.asistenciases = asistenciases;
    }




}


