package aplicacion.modelo.dominio;
// Generated 07/06/2018 13:36:05 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.Alumno;
import java.util.HashSet;
import java.util.Set;

/**
 * InscripcionesAlumnos generated by hbm2java
 */
public class InscripcionAlumno  implements java.io.Serializable {


     private Integer insCodigo;
     private Alumno alumno;
     private DocenteMateria docentesMaterias;
     private boolean insEstado;
     private Set asistenciases = new HashSet(0);

    public InscripcionAlumno() {
    }

	
    public InscripcionAlumno(Alumno alumno, DocenteMateria docentesMaterias, boolean insEstado) {
        this.alumno = alumno;
        this.docentesMaterias = docentesMaterias;
        this.insEstado = insEstado;
    }
    public InscripcionAlumno(Alumno alumno, DocenteMateria docentesMaterias, boolean insEstado, Set asistenciases) {
       this.alumno = alumno;
       this.docentesMaterias = docentesMaterias;
       this.insEstado = insEstado;
       this.asistenciases = asistenciases;
    }
   
    public Integer getInsCodigo() {
        return this.insCodigo;
    }
    
    public void setInsCodigo(Integer insCodigo) {
        this.insCodigo = insCodigo;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumnos (Alumno alumno) {
        this.alumno = alumno;
    }
    public DocenteMateria getDocentesMaterias() {
        return this.docentesMaterias;
    }
    
    public void setDocentesMaterias(DocenteMateria docentesMaterias) {
        this.docentesMaterias = docentesMaterias;
    }
    public boolean isInsEstado() {
        return this.insEstado;
    }
    
    public void setInsEstado(boolean insEstado) {
        this.insEstado = insEstado;
    }
    public Set getAsistenciases() {
        return this.asistenciases;
    }
    
    public void setAsistenciases(Set asistenciases) {
        this.asistenciases = asistenciases;
    }




}


