package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InscripcionAlumno generated by hbm2java
 */
public class InscripcionAlumno  implements java.io.Serializable {


     private Integer codigo;
     private Alumno alumno;
     private DocenteMateria docenteMateria;
     private boolean estado;
     

    public InscripcionAlumno() {
    }

    public InscripcionAlumno(Integer codigo, Alumno alumno, DocenteMateria docenteMateria, boolean estado) {
        this.codigo = codigo;
        this.alumno = alumno;
        this.docenteMateria = docenteMateria;
        this.estado = estado;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Alumno getAlumno() {
        return alumno;
    }

    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    public DocenteMateria getDocenteMateria() {
        return docenteMateria;
    }

    public void setDocenteMateria(DocenteMateria docenteMateria) {
        this.docenteMateria = docenteMateria;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

	
   




}


