package aplicacion.modelo.dominio;
// Generated 07/06/2018 13:36:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer matCodigo;
     private Carrera carrera;
     private String matNombre;
     private boolean matEstado;
     private Set docentesMateriases = new HashSet(0);

    public Materia() {
    }

	
    public Materia(Carrera carrera, String matNombre, boolean matEstado) {
        this.carrera = carrera;
        this.matNombre = matNombre;
        this.matEstado = matEstado;
    }
    public Materia(Carrera carrera, String matNombre, boolean matEstado, Set docentesMateriases) {
       this.carrera = carrera;
       this.matNombre = matNombre;
       this.matEstado = matEstado;
       this.docentesMateriases = docentesMateriases;
    }
   
    public Integer getMatCodigo() {
        return this.matCodigo;
    }
    
    public void setMatCodigo(Integer matCodigo) {
        this.matCodigo = matCodigo;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getMatNombre() {
        return this.matNombre;
    }
    
    public void setMatNombre(String matNombre) {
        this.matNombre = matNombre;
    }
    public boolean isMatEstado() {
        return this.matEstado;
    }
    
    public void setMatEstado(boolean matEstado) {
        this.matEstado = matEstado;
    }
    public Set getDocentesMateriases() {
        return this.docentesMateriases;
    }
    
    public void setDocentesMateriases(Set docentesMateriases) {
        this.docentesMateriases = docentesMateriases;
    }




}


