package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer matCodigo;
     private Carrera carreras;
     private String matNombre;
     private boolean matEstado;
     private Set docentesMateriases = new HashSet(0);

    public Materia() {
    }

	
    public Materia(Carrera carreras, String matNombre, boolean matEstado) {
        this.carreras = carreras;
        this.matNombre = matNombre;
        this.matEstado = matEstado;
    }
    public Materia(Carrera carreras, String matNombre, boolean matEstado, Set docentesMateriases) {
       this.carreras = carreras;
       this.matNombre = matNombre;
       this.matEstado = matEstado;
       this.docentesMateriases = docentesMateriases;
    }
   
    public Integer getMatCodigo() {
        return this.matCodigo;
    }
    
    public void setMatCodigo(Integer matCodigo) {
        this.matCodigo = matCodigo;
    }
    public Carrera getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carrera carreras) {
        this.carreras = carreras;
    }
    public String getMatNombre() {
        return this.matNombre;
    }
    
    public void setMatNombre(String matNombre) {
        this.matNombre = matNombre;
    }
    public boolean isMatEstado() {
        return this.matEstado;
    }
    
    public void setMatEstado(boolean matEstado) {
        this.matEstado = matEstado;
    }
    public Set getDocentesMateriases() {
        return this.docentesMateriases;
    }
    
    public void setDocentesMateriases(Set docentesMateriases) {
        this.docentesMateriases = docentesMateriases;
    }




}


