package aplicacion.modelo.dominio;
// Generated 07/06/2018 13:36:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfiles generated by hbm2java
 */
public class Perfile  implements java.io.Serializable {


     private Integer perCodigo;
     private Usuario usuarios;
     private String perNombres;
     private String perApellidos;
     private String perDni;
     private Date perFechaNac;
     private String perEmail;
     private String perCelular;
     private Set docenteses = new HashSet(0);
     private Set alumnoses = new HashSet(0);

    public Perfile() {
    }

	
    public Perfile(Usuario usuarios, String perNombres, String perApellidos, String perDni, Date perFechaNac, String perEmail, String perCelular) {
        this.usuarios = usuarios;
        this.perNombres = perNombres;
        this.perApellidos = perApellidos;
        this.perDni = perDni;
        this.perFechaNac = perFechaNac;
        this.perEmail = perEmail;
        this.perCelular = perCelular;
    }
    public Perfile(Usuario usuarios, String perNombres, String perApellidos, String perDni, Date perFechaNac, String perEmail, String perCelular, Set docenteses, Set alumnoses) {
       this.usuarios = usuarios;
       this.perNombres = perNombres;
       this.perApellidos = perApellidos;
       this.perDni = perDni;
       this.perFechaNac = perFechaNac;
       this.perEmail = perEmail;
       this.perCelular = perCelular;
       this.docenteses = docenteses;
       this.alumnoses = alumnoses;
    }
   
    public Integer getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Integer perCodigo) {
        this.perCodigo = perCodigo;
    }
    public Usuario getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuario usuarios) {
        this.usuarios = usuarios;
    }
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }
    public String getPerApellidos() {
        return this.perApellidos;
    }
    
    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }
    public String getPerDni() {
        return this.perDni;
    }
    
    public void setPerDni(String perDni) {
        this.perDni = perDni;
    }
    public Date getPerFechaNac() {
        return this.perFechaNac;
    }
    
    public void setPerFechaNac(Date perFechaNac) {
        this.perFechaNac = perFechaNac;
    }
    public String getPerEmail() {
        return this.perEmail;
    }
    
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail;
    }
    public String getPerCelular() {
        return this.perCelular;
    }
    
    public void setPerCelular(String perCelular) {
        this.perCelular = perCelular;
    }
    public Set getDocenteses() {
        return this.docenteses;
    }
    
    public void setDocenteses(Set docenteses) {
        this.docenteses = docenteses;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }




}


