package aplicacion.modelo.dominio;
// Generated 18/06/2018 06:49:42 PM by Hibernate Tools 4.3.1


import java.util.Date;


/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer codigo;
     private Usuario usuario;
     private String nombres;
     private String apellidos;
     private String dni;
     private Date fechaNac;
     private String email;
     private String celular;
     

    public Perfil() {
        usuario= new Usuario();
    }

	
    public Perfil(Usuario usuarios, String perNombres, String perApellidos, String perDni, Date perFechaNac, String perEmail, String perCelular) {
        this.usuario = usuarios;
        this.nombres = perNombres;
        this.apellidos = perApellidos;
        this.dni = perDni;
        this.fechaNac = perFechaNac;
        this.email = perEmail;
        this.celular = perCelular;
    }
    
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    

}


